name: Test build with mininal versions

on:
  # On a pull request that edits one of the following:
  pull_request:
    path:
      # This workflow file
      - '.github/workflow/check-opam-minimals.yml'
      # Definition of herdtools project
      - 'herdtools.opam'
      # Definition of aslref.opam
      - 'asllib/dune-project'

  # On demand
  workflow_dispatch:

  # Schedule every Tuesday, early in the morning
  schedule:
      - cron: '0 2 * * 2'

# Copy-pasted from https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml 4.08
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.08.1
      - run: |
          opam install . --deps-only --with-test --solver=builtin-mccs+glpk --criteria="-new"
          opam exec -- make build test install DUNE_PROFILE=dev
