name: Run Litmus

on:
  pull_request:
    paths:
      - '.github/workflows/run-litmus.yml'
      - 'litmus/**'
  schedule:
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - os: ubuntu-latest
            make-test-target: litmus-x86_64-test X86_64_PREFIX=''
          - os: ubuntu-24.04-arm
            make-test-target: litmus-aarch64-test
        ocaml-compiler:
          - 5

    runs-on: ${{ matrix.arch.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install qemu
        run: sudo apt update && sudo apt install qemu-system -qq

      - name: Install opam dependencies
        run: opam install . --deps-only

      - name: Build local dependencies
        run: |
          opam exec -- make Version.ml
          opam exec -- dune build litmus/litmus.exe internal/check_obs.exe

      - name: Run tests
        run: make ${{ matrix.arch.make-test-target }} LITMUS=${LITMUS}
        env:
          ACCEL: tcg
          LITMUS: ${{ github.workspace }}/_build/default/litmus/litmus.exe
